# Generated by Django 5.0.4 on 2024-06-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listing_title', models.CharField(max_length=30)),
                ('listing_description', models.CharField(max_length=90)),
                ('starting_bid', models.IntegerField()),
                ('listing_image', models.URLField()),
            ],
        ),
    ]
